[package]
name = "ffmpeg-cpal-play-audio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.4"
ffmpeg-next = "4.4.0"
ringbuf = "0.2.6"
